/**
 * Fixed disclaimer text shown on every report and on the dashboard footer.
 * Bilingual — rendered based on current i18n language.
 *
 * Kept in a single file so wording edits live in one place.
 */

export const DISCLAIMER_EN =
  'The radar report is generated by a third-party AI based on publicly collected information, for Amazon internal reference only. Recipients must verify and validate original information before using as a basis for decisions. Unverified market intelligence should not be shared with any external third parties. Any risks arising from using unverified report content are borne by the user.';

export const DISCLAIMER_ZH =
  '雷达报告由第三方 AI 生成，内容基于公开渠道收集，仅供亚马逊内部参考。接收方须在使用前依据原始信息进行核实及验证，方可作为决策依据。未经核实及验证的市场情报不得分享给任何外部第三方，因使用未进一步核实的报告内容而产生的任何风险，由使用者自行承担。';

export const DISCLAIMER_TITLE_EN = 'Disclaimer';
export const DISCLAIMER_TITLE_ZH = '免责声明';

export function getDisclaimer(lang: string): {
  title: string;
  body: string;
} {
  const isZh = lang?.toLowerCase().startsWith('zh');
  return isZh
    ? { title: DISCLAIMER_TITLE_ZH, body: DISCLAIMER_ZH }
    : { title: DISCLAIMER_TITLE_EN, body: DISCLAIMER_EN };
}
